

# Application Information
ios_app_id: 1400384964

page_title: Egghart - The Egg Timer
enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.
app_name: Egghart - The Egg Timer # Automatically populates if not set and if iOS app ID is set.
app_price: 0.99$ # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.

app_description: |
  The cozy sunday morning breakfast is served. Delicious rolls, orange juice, everything seems perfect – but the breakfast egg is rock hard cooked.

  <br/><br/>The drama is over: Egghart - The egg timer for your perfect breakfast egg.

appstore_link: https://apps.apple.com/de/app/egghart-die-eieruhr/id1400384964?mt=8 # Automatically populates if not set and if iOS app ID is set.
#playstore_link: # Enter Google Play Store URL.
#presskit_download_link: "assets/presskit.zip" # Enter a link to downloadable file or upload your press kit file to assets


# Information About Yourself
your_name: Markus Winter
your_link: https://wntr.me
partner_name: Dana Saager
partner_link: https://danasaager.de
your_city: Hamburg, Germany
email_address: support@egghart.app

twitter_username: markuswntr
github_username: markuswntr
#facebook_username:
#instagram_username:
#youtube_username:


# Feature List                            Edit, add or remove features to be presented.
# features                                  :

#   - title                                 : GitHub Pages Jekyll Theme
#     description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
#     fontawesome_icon_name                 : magic
    
#   - title                                 : iPhone Device Preview
#     description                           : Preview your app in the context of an iPhone device. Five different device colors included.
#     fontawesome_icon_name                 : mobile

#   - title                                 : Video Support
#     description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
#     fontawesome_icon_name                 : play-circle

#   - title                                 : Automatic Icon and Metadata
#     description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
#     fontawesome_icon_name                 : sync

#   - title                                 : Easy to Tweak
#     description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : adjust
  
#   - title                                 : Feature List
#     description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : star

#   - title                                 : Smart App Banner
#     description                           : Display a smart app banner on iOS devices.
#     fontawesome_icon_name                 : arrow-alt-circle-down

#   - title                                 : Social Links
#     description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : link

#   - title                                 : FontAwesome Support
#     description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
#     fontawesome_icon_name                 : info-circle

#   - title                                 : # New Feature Title
#     description                           : # New Feature Description
#     fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 1.0
topbar_title_color                        : "#070707"

#cover_image                               : assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 1.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ebebeb"

link_color                                : "#1d63ea"

app_title_color                           : "#070707"
app_price_color                           : "#070707"
app_description_color                     : "#070707"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown